const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.ScriptsInEvents.Folhagameover_Event2_Act1,
		C3.ScriptsInEvents.Folhastart_Event3_Act1,
		C3.ScriptsInEvents.Folhastart_Event5_Act1
	];
};
self.C3_JsPropNameTable = [
	{aDir: 0},
	{dot: 0},
	{BigDot: 0},
	{Muro: 0},
	{Navegador: 0},
	{TileSize: 0},
	{Score: 0},
	{Lives: 0},
	{PlayerRespawn: 0},
	{nbGHOST: 0},
	{bigDotScore: 0},
	{dotScore: 0},
	{ghostEscapeTime: 0},
	{ghostBlinkTime: 0},
	{Alive: 0},
	{GAME: 0},
	{Direction: 0},
	{MoveDuration: 0},
	{name: 0},
	{Vert: 0},
	{hor: 0},
	{escape: 0},
	{eaten: 0},
	{escapeBlink: 0},
	{DestruirForaDoLayout: 0},
	{Projétil: 0},
	{Cronômetro: 0},
	{Ghost: 0},
	{ghostSpawn: 0},
	{Teclado: 0},
	{directiom: 0},
	{moveDuration: 0},
	{dirCharge: 0},
	{Player: 0},
	{ID: 0},
	{playerLivies: 0},
	{PlayerSpawner: 0},
	{Texto: 0},
	{Piscar: 0},
	{txtGUI: 0},
	{Esmaecer: 0},
	{txtScore: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Muro2: 0},
	{Muro3: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{APPLEMEN: 0},
	{texturapicnic: 0},
	{START: 0},
	{startMaça: 0},
	{SobreMaça: 0},
	{sobre: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Mouse: 0},
	{Sprite: 0},
	{AudioDeInteração: 0},
	{Sprite2: 0},
	{ceu: 0},
	{X: 0},
	{TextoJS: 0},
	{PlayerSpawner2: 0}
];

self.InstanceType = {
	aDir: class extends self.IArrayInstance {},
	dot: class extends self.ISpriteInstance {},
	BigDot: class extends self.ISpriteInstance {},
	Muro: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	GAME: class extends self.ISpriteInstance {},
	Ghost: class extends self.ISpriteInstance {},
	ghostSpawn: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	playerLivies: class extends self.ISpriteInstance {},
	PlayerSpawner: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	txtGUI: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Muro2: class extends self.ISpriteInstance {},
	Muro3: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	APPLEMEN: class extends self.ITextInstance {},
	texturapicnic: class extends self.ITiledBackgroundInstance {},
	START: class extends self.ITextInstance {},
	startMaça: class extends self.ISpriteInstance {},
	SobreMaça: class extends self.ISpriteInstance {},
	sobre: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	AudioDeInteração: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ceu: class extends self.ISpriteInstance {},
	X: class extends self.ITextInstance {},
	TextoJS: class extends self.ITextInstance {},
	PlayerSpawner2: class extends self.ISpriteInstance {}
}